In [30]:
import pandas as pd
df = pd.read_json('/workspaces/Edu_Math_tutor/single_error.jsonl', lines = True)
#df.to_json('single_error.jsonl', force_ascii= False, orient= 'records', lines=True)

In [31]:
df

,topic,question,correct_answer,full_answer,wrong_solution,explanation,error_type,bloom_level
0,"Hoán vị, tổ hợp, chỉnh hợp",Có 5 nam sinh và 3 nữ sinh cần được xếp vào mộ...,None,None,Xét câu b) Xếp học sinh cùng giới đứng cạnh nh...,Lời giải đã bỏ qua một bước quan trọng. Sau kh...,[MS],3.0
1,"Hoán vị, tổ hợp, chỉnh hợp",Có 5 nam sinh và 3 nữ sinh cần được xếp vào mộ...,None,None,Xét câu d) Xếp học sinh nam luôn đứng cạnh nha...,Học sinh đã xác định đúng các bước cần làm như...,[OP],3.0
2,"Hoán vị, tổ hợp, chỉnh hợp",Một trường THPT X có 8 giáo viên Toán gồm có 3...,None,None,Xét câu c) Chọn 1 giáo viên nam môn Toán và 1 ...,Việc chọn một giáo viên nam môn Toán và một gi...,[OP],3.0
3,"Hoán vị, tổ hợp, chỉnh hợp",Một trường THPT X có 8 giáo viên Toán gồm có 3...,None,None,Xét câu d) Chọn đoàn 3 người có đủ 2 môn và đủ...,Lời giải đã thiếu một trường hợp quan trọng là...,[MS],3.0
4,"Hoán vị, tổ hợp, chỉnh hợp","Có 5 bông hồng, 4 bông trắng (mỗi bông đều khá...",None,None,Xét câu b) Số cách chọn 4 bông mà số bông mỗi ...,"Lập luận của bài giải là đúng, tuy nhiên đã có...",[CAL],3.0
...,...,...,...,...,...,...,...,...
1025,Vị trí tương đối trong mp toạ độ,"Câu 5: Trong mặt phẳng tọa độ Oxy, cho điểm A(...",None,None,Đường thẳng Δ cách đều hai điểm A và M khi và ...,Lý luận sai (REAS) khi học sinh chỉ xét một tr...,"[REAS, CAL]",NaN
1026,Vị trí tương đối trong mp toạ độ,Câu 1: Viết phương trình tổng quát của đường t...,None,None,"Đường thẳng Δ có VTPT là $\vec{n}_{\Delta}=(3,...",Học sinh đã áp dụng sai công thức (FC) khi cho...,"[FC, CAL]",NaN
1027,Vị trí tương đối trong mp toạ độ,Câu 1: Viết phương trình tổng quát của đường t...,None,None,"Đường thẳng Δ có VTPT là $\vec{n}_{\Delta}=(3,...",Học sinh có lý luận (REAS) đúng về mối quan hệ...,"[FC, REAS]",NaN
1028,Vị trí tương đối trong mp toạ độ,Câu 2: Tìm giá trị thực của tham số m để ba đư...,None,None,"Để ba đường thẳng đồng quy, chúng phải cùng đi...",Học sinh có hướng lý luận (REAS) đúng là tìm g...,"[CAL, REAS]",NaN
1029,Vị trí tương đối trong mp toạ độ,Câu 2: Tìm giá trị thực của tham số m để ba đư...,None,None,"Để ba đường thẳng d₁, d₂, d₃ đồng quy, định th...",Học sinh đã cố gắng áp dụng một phương pháp nâ...,"[FC, REAS, CAL]",NaN

In [1]:
import pandas as pd
import json

# Load JSON file
with open("/workspaces/Edu_Math_tutor/wrong_answer/question_1.json", "r", encoding="utf-8") as f:
    data = json.load(f)

# Step 1: Go inside wrong_solutions, keep meta
df = pd.json_normalize(
    data,
    record_path=["wrong_solutions"],            # dive into wrong_solutions
    meta=["question"]                           # keep question for context
)

# Step 2: Explode applied_errors (list of dicts)
df = df.explode("applied_errors")

# Step 3: Flatten applied_errors into separate columns
df = pd.concat(
    [df.drop(columns=["applied_errors"]),
     df["applied_errors"].apply(pd.Series)], 
    axis=1
)

# Reorder columns for clarity
df = df[[
    "question", 
    "transformed_solution", 
    "wrong_step", 
    "error_type", 
    "description", 
    "is_single_error", 
    "notes"
]]

print(df)

                                            question  \
0  Xét phép thử "Gieo một xúc sắc cân đối và đồng...
1  Xét phép thử "Gieo một xúc sắc cân đối và đồng...
2  Xét phép thử "Gieo một xúc sắc cân đối và đồng...
3  Xét phép thử "Gieo một xúc sắc cân đối và đồng...
4  Xét phép thử "Gieo một xúc sắc cân đối và đồng...
5  Xét phép thử "Gieo một xúc sắc cân đối và đồng...
6  Xét phép thử "Gieo một xúc sắc cân đối và đồng...

                                transformed_solution  wrong_step error_type  \
0  Xúc sắc có 6 mặt, các mặt có số chấm từ 1 đến ...           5        MIS
1  Xúc sắc có 6 mặt. \nA. Mặt xuất hiện có số chấ...           5        MIS
2  Xúc sắc có 6 mặt, các mặt có số chấm từ 1 đến ...           1         HA
3  Xúc sắc có 6 mặt. \nA. Mặt xuất hiện có số chấ...           5       REAS
4  Xúc sắc có 6 mặt. \nA. Mặt xuất hiện có số chấ...           5         HA
5  Xúc sắc có 6 mặt. \nA. Mặt xuất hiện có số chấ...           5        MIS
6  Xúc sắc có 6 mặt. \nA. Mặt xuất hiện có số chấ...           5       REAS

                                         description is_single_error  \
0  Misinterpreted the question. The question asks...            true
1  Misinterpreted the question. The student selec...            true
2  Introduced the concept of probability without ...            true
3  Incorrect reasoning. The student chose A based...            true
4  Introduced an irrelevant statement ('7 is a lu...            true
5  Misinterpreted the question. The student selec...            true
6  Incorrect reasoning. The student chose B based...            true

                                               notes
0  The student understood the concept of impossib...
1  The student failed to understand the definitio...
2  The student unnecessarily brought in the conce...
3  The student's reasoning is completely illogica...
4  The student's justification is based on a supe...
5  The student failed to understand the definitio...
6  The student's reasoning is completely illogica...

In [6]:
questions = df['question'].unique()

In [8]:
questions_df = pd.DataFrame(questions, columns=['question'])

In [11]:
questions_df.to_csv("unique_questions.csv", index=False)

In [27]:
prompt_template = """You are given a math problem as input.
{question}
Your task is to generate several wrong answers in the style of a student’s handwritten solution. The wrong answers should feel natural and realistic, including errors such as: misunderstanding the problem, misusing formulas, calculation mistakes, or flawed reasoning.

When you write the wrong solution:

Show the step-by-step solution as if a student is solving it.

Intentionally insert multiple errors of forms (conceptual, logical, arithmetic, comprehension, etc.).

Make the mistakes look plausible, not random—like what a student would naturally do.

After writing the wrong solution, list all the errors you made and classify each into one of these categories:

🔹 Error Taxonomy

1. Lỗi Tính toán (Calculation Errors)

CAL: Lỗi tính toán số học (Arithmetic miscalculation)

UC: Sai khi đổi/nhầm đơn vị (Unit conversion mistake)

OP: Sử dụng toán tử không đúng (Operator misuse)

CO: Lỗi đếm, sai số lượng hoặc chỉ số (Counting/index mistake)

2. Lỗi Khái niệm (Conceptual Errors)

FC: Nhầm lẫn hoặc áp dụng sai công thức (Formula confusion)

KNOW: Nhớ hoặc hiểu sai kiến thức (Knowledge misunderstanding)

CV: Gán sai thuộc tính giá trị (Wrong value attribution)

3. Lỗi Logic (Logical Errors)

REAS: Lý luận sai, suy luận không đúng (Faulty reasoning)

MS: Thiếu bước trung gian quan trọng (Missing step)

CS: Các bước mâu thuẫn lẫn nhau (Contradiction in steps)

HA: Thêm thông tin bịa/không liên quan (Hallucinated info)

4. Lỗi Đọc hiểu (Comprehension Errors)

MIS: Hiểu sai yêu cầu đề bài (Misunderstood the question)

📌 Output Format

The output must be the original JSON input plus an additional field:

{{
  "question": "...",
  "wrong_answers": [
    {{
      "error_solution": "Step-by-step wrong solution here...",
      "error_type": ["CAL", "KNOW"],
      "explanation":"....."
}},
    {{
      "error_solution": "Another wrong solution with different mistakes...",
      "error_type": ["MIS", "FC"],
      "explanation":"...."
    }}
  ]
}}
"error_solution" = the full wrong solution written as if by a student.

"error_type" = list of all error codes that appear in that solution.
"explanation" = explanation for the error_solution
"""

In [28]:
from langchain_core.prompts import PromptTemplate
from langchain_google_genai import ChatGoogleGenerativeAI
import pandas as pd
import dotenv
import os
dotenv.load_dotenv()
os.environ["GOOGLE_API_KEY"] = os.getenv("GEMINI_API")

df = pd.read_json('selected_questions.json')
reasoning_model = "models/gemma-3-27b-it"
#llm_reasoning = ChatGoogleGenerativeAI(model=reasoning_model, temperature=0.2, top_p=0.9)
prompt = PromptTemplate.from_template(prompt_template)
import json
import re

def generate_wrong_solutions(llm_reasoning, question, file_path="wrong_solutions.jsonl"):
    chain = prompt | llm_reasoning
    raw_output = chain.invoke({"question": question}).content

    # Step 1: Extract JSON part with regex
    match = re.search(r"\{.*\}", raw_output, re.DOTALL)
    if match:
        json_text = match.group(0)
    else:
        # fallback if no JSON found
        json_text = None

    # Step 2: Parse into Python dict
    try:
        result_json = json.loads(json_text)
    except json.JSONDecodeError:
        result_json = None

    # Step 3: Append to JSONL file
    with open(file_path, "a", encoding="utf-8") as f:
        f.write(json.dumps(result_json, ensure_ascii=False) + "\n")

    # Optional: return if you want to use it in code
    #return result_json

In [34]:
import random
for i in range(2):
  temp = random.uniform(0.2, 0.7)   # pick random temp in [0.2, 0.7]
  top_p = random.uniform(0.7, 0.9)  # pick random top_p in [0.7, 0.9]
  llm = ChatGoogleGenerativeAI(
        model=reasoning_model,
        temperature=temp,
        top_p=top_p,
    )
  for index, row in df.iterrows():
      print(row)
      generate_wrong_solutions(llm, row['question'])
      break

topic                           Hệ bất phương trình bậc nhất hai ẩn
question          Cho hệ bất phương trình { 2y - 2x ≤ 2; 2y - x ...
correct_answer                                                 None
full_answer                                                    None
Name: 0, dtype: object
topic                           Hệ bất phương trình bậc nhất hai ẩn
question          Cho hệ bất phương trình { 2y - 2x ≤ 2; 2y - x ...
correct_answer                                                 None
full_answer                                                    None
Name: 0, dtype: object

In [ ]:
import os
from langchain_core.output_parsers import JsonOutputParser, StrOutputParser
from langchain_core.prompts import PromptTemplate
from langchain_google_genai import ChatGoogleGenerativeAI
import glob, re
import pandas as pd
# --- Environment Setup ---
import dotenv
dotenv.load_dotenv()
os.environ["GOOGLE_API_KEY"] = os.getenv("GEMINI_API")

DEFAULT_REASONING_MODEL = "models/gemma-3-27b-it"
#models/gemini-2.5-flash
DEFAULT_FAST_MODEL = "models/gemma-3-27b-it"
wrong_answer_dir = "//workspaces//Edu_Math_tutor//test"

def natural_key(s):
    return [int(text) if text.isdigit() else text.lower()
            for text in re.split(r'(\d+)', s)]

csv_files = sorted(glob.glob(os.path.join(wrong_answer_dir, "student_error_*.csv")), key=natural_key)
prompt_template ="""Evaluate the error_analysis {error_analysis} against the groud truth explanation {explanation}.
                        You return a json structure:
                        point: 1 if error_analysis match ground truth, 0 if not.
                        reason: explain why.
                     """
llm = ChatGoogleGenerativeAI(model=DEFAULT_REASONING_MODEL, temperature=0.2)
prompt = PromptTemplate.from_template(prompt_template)
chain = prompt | llm
for file in csv_files:
    df = pd.read_csv(file)
    df['res'] = None
    for index, row in df.iterrows():
        res = chain.invoke({"error_analysis": row['agent_analysis'], "explanation": row['explanation']})
        df.at[index, 'res'] = res
    df.to_csv(file)

In [15]:
df = pd.read_csv(csv_files[2])
df

,Unnamed: 0.1,Unnamed: 0,topic,question,correct_answer,full_answer,wrong_solution,explanation,Errortype,bloom_level,agent_analysis,res
0,0,0,"Hoán vị, tổ hợp, chỉnh hợp",Có 5 nam sinh và 3 nữ sinh cần được xếp vào mộ...,NaN,NaN,Xét câu b) Xếp học sinh cùng giới đứng cạnh nh...,Lời giải đã bỏ qua một bước quan trọng. Sau kh...,Missing Step (MS),3,detailed_analysis='Học sinh mắc lỗi trong việc...,"content='```json\n{\n ""point"": 1,\n ""reason""..."
1,1,1,"Hoán vị, tổ hợp, chỉnh hợp",Có 5 nam sinh và 3 nữ sinh cần được xếp vào mộ...,NaN,NaN,Xét câu d) Xếp học sinh nam luôn đứng cạnh nha...,Học sinh đã xác định đúng các bước cần làm như...,Operator Error (OP),3,detailed_analysis='Học sinh mắc lỗi trong việc...,"content='```json\n{\n ""point"": 1,\n ""reason""..."
2,2,2,"Hoán vị, tổ hợp, chỉnh hợp",Một trường THPT X có 8 giáo viên Toán gồm có 3...,NaN,NaN,Xét câu c) Chọn 1 giáo viên nam môn Toán và 1 ...,Việc chọn một giáo viên nam môn Toán và một gi...,Operator Error (OP),3,detailed_analysis='Phân tích từ các detector c...,"content='```json\n{\n ""point"": 0,\n ""reason""..."
3,3,3,"Hoán vị, tổ hợp, chỉnh hợp",Một trường THPT X có 8 giáo viên Toán gồm có 3...,NaN,NaN,Xét câu d) Chọn đoàn 3 người có đủ 2 môn và đủ...,Lời giải đã thiếu một trường hợp quan trọng là...,Missing Step (MS),3,detailed_analysis='Phân tích các lỗi cho thấy ...,"content='```json\n{\n ""point"": 1,\n ""reason""..."
4,4,4,"Hoán vị, tổ hợp, chỉnh hợp","Có 5 bông hồng, 4 bông trắng (mỗi bông đều khá...",NaN,NaN,Xét câu b) Số cách chọn 4 bông mà số bông mỗi ...,"Lập luận của bài giải là đúng, tuy nhiên đã có...",Calculation Error (CAL),3,detailed_analysis='Phân tích từ các detector c...,"content='```json\n{\n ""point"": 0,\n ""reason""..."
5,5,5,"Hoán vị, tổ hợp, chỉnh hợp","Có 5 bông hồng, 4 bông trắng (mỗi bông đều khá...",NaN,NaN,Xét câu d) Số cách chọn 4 bông có đủ hai màu:\...,Phương pháp giải này dẫn đến việc đếm lặp các ...,Reasoning Error (REAS),3,"detailed_analysis=""Bài giải câu d) mắc phải lỗ...","content='```json\n{\n ""point"": 1,\n ""reason""..."
6,6,6,"Hoán vị, tổ hợp, chỉnh hợp",Cho hai đường thẳng song song d₁ và d₂. Trên d...,NaN,NaN,Tổng số điểm là 17 + 20 = 37 điểm.\nĐể tạo thà...,Lời giải đã không xét đến điều kiện để tạo thà...,Knowledge Error (KNOW),3,detailed_analysis='Bài giải mắc các lỗi về mặt...,"content='```json\n{\n ""point"": 1,\n ""reason""..."
7,7,7,"Hoán vị, tổ hợp, chỉnh hợp",Cho hai đường thẳng song song d₁ và d₂. Trên d...,NaN,NaN,"Để tạo thành một tam giác, các đỉnh không được...",Học sinh đã xác định đúng số lượng các bộ điểm...,Misinterpretation of the Question (MIS),3,detailed_analysis='Bài giải thể hiện sự nhầm l...,"content='```json\n{\n ""point"": 1,\n ""reason""..."
8,8,8,"Hoán vị, tổ hợp, chỉnh hợp","Cho 10 điểm phân biệt A₁, A₂,..., A₁₀ trong đó...",NaN,NaN,Số cách chọn 3 điểm bất kỳ từ 10 điểm đã cho l...,Lời giải đã bỏ qua bước quan trọng nhất là loạ...,Missing Step (MS),3,detailed_analysis='Học sinh gặp vấn đề trong v...,"content='```json\n{\n ""point"": 1,\n ""reason""..."
9,9,9,"Hoán vị, tổ hợp, chỉnh hợp","Cho 10 điểm phân biệt A₁, A₂,..., A₁₀ trong đó...",NaN,NaN,Ta sẽ đếm trực tiếp số tam giác.\nCác điểm đượ...,"Phương pháp đếm trực tiếp là hợp lệ, nhưng lời...",Missing Step (MS),3,detailed_analysis='Bài giải của học sinh mắc l...,"content='```json\n{\n ""point"": 1,\n ""reason""..."
10,10,10,"Hoán vị, tổ hợp, chỉnh hợp",Đội văn nghệ của nhà trường gồm 4 học sinh lớp...,NaN,NaN,"Để đảm bảo lớp nào cũng có học sinh, ta làm nh...",Đây là một lỗi lập luận kinh điển khi giải bài...,Reasoning Error (REAS),4,detailed_analysis='Bài giải của học sinh mắc l...,"content='```json\n{\n ""point"": 1,\n ""reason""..."
11,11,11,"Hoán vị, tổ hợp, chỉnh hợp",Đội văn nghệ của nhà trường gồm 4 học sinh lớp...,NaN,NaN,Ta sử dụng phương pháp phần bù.\n- Tổng số các...,"Phương pháp phần bù là đúng, nhưng lời giải đã...",Missing Step (MS),4,"detailed_analysis=""Bài giải mắc lỗi trong việc...","content='```json\n{\n ""point"": 0,\n ""reason""..."
12,12,12,"Hoán vị, tổ hợp, chỉnh hợp",Có bao nhiêu số tự nhiên chia hết cho 2 mà mỗi...,NaN,NaN,Gọi số cần tìm là abc.\n- Vì số chia hết cho 2...,Lập luận này có một lỗ hổng. Số cách chọn cho ...,Reasoning Error (REAS),3,detailed_analysis='Học sinh mắc lỗi trong việc...,"content='```json\n{\n ""point"": 1,\n ""reason""..."
13,13,13,"Hoán vị, tổ hợp, chỉnh hợp",Có bao nhiêu số tự nhiên chia hết cho 2 mà mỗi...,NaN,NaN,Gọi số cần tìm là abc.\n- a có 9 cách chọn (từ...,Thứ tự chọn các chữ số trong lời giải này dẫn ...,Reasoning Error (REAS),3,detailed_analysis='Bài giải mắc phải nhiều lỗi...,"content='```json\n{\n ""point"": 1,\n ""reason""..."
14,14,14,"Hoán vị, tổ hợp, chỉnh hợp",Lớp 10B có 15 bạn (trong đó có lớp trưởng) tha...,NaN,NaN,- Chọn 6 bạn từ 15 bạn để xếp vào đội hình: C⁶...,Lời giải đã nhầm lẫn giữa quy tắc cộng và quy ...,Operator Error (OP),3,detailed_analysis='Bài giải của học sinh mắc p...,"content='```json\n{\n ""point"": 1,\n ""reason""..."
15,15,15,"Hoán vị, tổ hợp, chỉnh hợp",Lớp 10B có 15 bạn (trong đó có lớp trưởng) tha...,NaN,NaN,- Vị trí cuối cùng dành cho lớp trưởng: có 1 c...,Lời giải đã chọn đúng 5 bạn còn lại nhưng quên...,Formula Confusion Error (FC),3,detailed_analysis='Học sinh mắc lỗi cơ bản tro...,"content='```json\n{\n ""point"": 1,\n ""reason""..."
16,16,16,"Hoán vị, tổ hợp, chỉnh hợp",Cho hai dãy ghế được xếp như sau: Dãy 1 (Ghế 1...,NaN,NaN,Yêu cầu mỗi bạn nam ngồi đối diện với một bạn ...,Lời giải đã có một bước thừa và sai lầm trong ...,Reasoning Error (REAS),3,detailed_analysis='Bài giải mắc phải nhiều lỗi...,"content='```json\n{\n ""point"": 1,\n ""reason""..."
17,17,17,"Hoán vị, tổ hợp, chỉnh hợp",Cho hai dãy ghế được xếp như sau: Dãy 1 (Ghế 1...,NaN,NaN,"Để có 4 cặp nam-nữ đối diện, ta cần chọn 4 nam...",Lời giải này chỉ xét một trường hợp là nam ngồ...,Missing Step (MS),3,detailed_analysis='Bài giải của học sinh mắc p...,"content='```json\n{\n ""point"": 1,\n ""reason""..."
18,18,18,"Hoán vị, tổ hợp, chỉnh hợp",Cho đa giác đều có 100 đỉnh. Hỏi có bao nhiêu ...,NaN,NaN,Một tam giác được tạo bởi 3 đỉnh của đa giác đ...,Lập luận này sai vì nó đếm tất cả các loại tam...,Reasoning Error (REAS),4,detailed_analysis='Bài giải của học sinh thể h...,"content='```json\n{\n ""point"": 1,\n ""reason""..."
19,19,19,"Hoán vị, tổ hợp, chỉnh hợp",Cho đa giác đều có 100 đỉnh. Hỏi có bao nhiêu ...,NaN,NaN,"Để tạo một tam giác tù, ta cần chọn 3 đỉnh.\n-...",Lời giải đã tính đúng tổng số tam giác và số t...,Missing Step (MS),4,detailed_analysis='Bài giải thể hiện sự nhầm l...,"content='```json\n{\n ""point"": 1,\n ""reason""..."
20,20,20,"Hoán vị, tổ hợp, chỉnh hợp",Cho hai đường thẳng d₁ và d₂ song song với nha...,NaN,NaN,Tổng số điểm là 10 + 7 = 17.\nSố cách chọn 3 đ...,Đây là lỗi kiến thức cơ bản. Lời giải đã không...,Knowledge Error (KNOW),3,detailed_analysis='Bài giải của học sinh mắc l...,"content='```json\n{\n ""point"": 1,\n ""reason""..."
21,21,21,"Hoán vị, tổ hợp, chỉnh hợp",Cho hai đường thẳng d₁ và d₂ song song với nha...,NaN,NaN,"Để tạo thành một tam giác, ta cần chọn các điể...",Học sinh đã xác định đúng hai trường hợp có th...,Operator Error (OP),3,detailed_analysis='Bài giải của học sinh mắc p...,"content='```json\n{\n ""point"": 1,\n ""reason""..."
22,22,22,"Hoán vị, tổ hợp, chỉnh hợp",Một công ty có 9 nam và 13 nữ trong đó có đúng...,NaN,NaN,"Tổng số người là 22. Có 2 cặp vợ chồng, tức là...","Phương pháp phần bù là đúng, các trường hợp vi...",Operator Error (OP),3,detailed_analysis='Bài giải mắc phải nhiều lỗi...,"content='```json\n{\n ""point"": 1,\n ""reason""..."
23,23,23,"Hoán vị, tổ hợp, chỉnh hợp",Một công ty có 9 nam và 13 nữ trong đó có đúng...,NaN,NaN,Ta sẽ chọn trực tiếp 5 người sao cho không có ...,Phương pháp đếm trực tiếp là hợp lệ nhưng đã t...,Missing Step (MS),3,"detailed_analysis=""Bài giải của học sinh mắc p...","content='```json\n{\n ""point"": 1,\n ""reason""..."
24,24,24,hàm số bậc hai,Câu 17: Gọi S là tập hợp tất cả các giá trị củ...,NaN,NaN,Hàm số bậc hai y = ax² + bx + c với a > 0 đồng...,Học sinh đã mắc hai lỗi. Lỗi thứ nhất là khi g...,"Operator Error (OP), Reasoning Error (REAS)",3,detailed_analysis='Học sinh mắc phải nhiều lỗi...,"content='```json\n{\n ""point"": 0,\n ""reason""..."
25,25,25,hàm số bậc hai,Câu 18: Tìm tất cả các giá trị dương của tham ...,NaN,NaN,"Hàm số f(x) = mx² - 4x - m² có a = m, b = -4. ...",Học sinh đã đưa ra một lập luận sai lầm rằng h...,"Missing Step (MS), Knowledge Error (KNOW)",3,detailed_analysis='Bài giải của học sinh mắc l...,"content='```json\n{\n ""point"": 1,\n ""reason""..."
26,26,26,hàm số bậc hai,Câu 19: Cho hàm số y = x² - 2mx + m² (P). Khi ...,NaN,NaN,Đỉnh của Parabol (P) có hoành độ x = -b/2a = -...,"Học sinh đã tìm đúng tọa độ đỉnh là I(m, 0). T...",NaN,4,"detailed_analysis=""Học sinh gặp vấn đề trong v...","content='```json\n{\n ""point"": 1,\n ""reason""..."
27,27,27,hàm số bậc hai,Câu 20: Cho hàm số y = x² - 4mx + 4m² (P). Khi...,NaN,NaN,Hàm số y = x² - 4mx + 4m² là dạng y = (x - 2m)...,"Học sinh đã tìm ra tọa độ đỉnh I(2m, 0) một cá...",NaN,4,detailed_analysis='Học sinh gặp lỗi trong việc...,"content='```json\n{\n ""point"": 0,\n ""reason""..."
28,28,28,hàm số bậc hai,Câu 20: Cho hàm số y = x² - 4mx + 4m² (P). Khi...,NaN,NaN,Tọa độ đỉnh của parabol là x = -b/2a = -(-4m)/...,Học sinh đã tìm đúng tọa độ đỉnh và thậm chí đ...,NaN,4,detailed_analysis='Bài giải của học sinh cho t...,"content='```json\n{\n ""point"": 1,\n ""reason""..."
29,29,29,hàm số bậc hai,Câu 40: Parabol y = ax² + bx + c đạt cực tiểu ...,NaN,NaN,"Parabol đi qua A(0;6) nên thay x=0, y=6 vào ph...",Học sinh đã mắc lỗi tính toán khi thay thế. Từ...,Calculation Error (CAL),3,detailed_analysis='Bài giải của học sinh thể h...,"content='```json\n{\n ""point"": 1,\n ""reason""..."
30,30,30,hàm số bậc hai,Câu 43: Cho (P): y = x² + bx + 1 đi qua điểm A...,NaN,NaN,Parabol đi qua điểm A(-1;3). Ta có hoành độ đỉ...,Học sinh đã nhầm lẫn giữa việc 'đi qua một điể...,NaN,3,detailed_analysis='Bài giải thể hiện sự nhầm l...,"content='```json\n{\n ""point"": 1,\n ""reason""..."

file 10: 8/10
file 20: 7/10